" Configuration file for vim
set modelines=0		" CVE-2007-2438

"****************joas settings**************
set nu

" sane tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4

"convert all typed tabs to spaces
set expandtab

syntax on

" search settings
set ignorecase
set smartcase
set incsearch
set hlsearch

set cursorline

set autoindent
set smartindent

"show file name
set laststatus=2
"*******************************************
" replace 120 for your desired code guidelines
" sets a vertical bar at column 120th
set colorcolumn=120
set tabpagemax=100

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set backspace=2		" more powerful backspacing

" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup nobackup
" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup nobackup

" ******************** Plugin section **************
" if plug is not installed then its installed
" automatically
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Control sintax highlighting
Plug 'burneyy/vim-winccoa'

Plug 'preservim/nerdtree'
" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()
