" Configuration file for vim
set modelines=0		" CVE-2007-2438

"****************joas settings**************
set nu

" sane tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4

"convert all typed tabs to spaces
set expandtab

syntax on

" search settings
set ignorecase
set smartcase
set incsearch
set hlsearch

set cursorline

set autoindent
set smartindent

" Fuzzy finder
set rtp+=/usr/local/opt/fzf 

"show file name
set laststatus=2
"*******************************************

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set backspace=2		" more powerful backspacing

" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup nobackup
" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup nobackup

"let skip_defaults_vim=1
"call pathogen#helptags()
